# ZSHRC
#
# This file is sourced by interactive shells.
# It should define aliases, functions, shell options, and key bindings.

# set options
export EDITOR='subl -w'
export VISUAL='subl -w'
[[ $OSTYPE == darwin* ]] && \
export BROWSER='open' || export BROWSER='xdg-open'
export PAGER='less'
export LESS='-F -g -i -M -R -S -w'
export TIMEFMT=$'\n\e[0;37m%J\n\e[1;35mreal\e[00m %*Es\t\e[1;35musr\e[00m %*Us\t\e[1;35msys\e[00m %*Ss\t\e[1;35mcpu\e[00m %P'
export DOTFILES=$HOME/code/notes/.dotfiles

# load files
test -e $HOME/.iterm2_shell_integration.zsh && \
source $HOME/.iterm2_shell_integration.zsh
source $DOTFILES/zsh/prezto/init.zsh
source $DOTFILES/zsh/aliases
source $DOTFILES/zsh/zle.zsh

# move this to functions/init.zsh?
# autoload compiled functions
for fn_dir in $DOTFILES/zsh/functions/*; do
	if [[ -d $fn_dir ]]; then
		zwc="${fn_dir}/${fn_dir:t}.zwc"
		zcompile -Uz $zwc $fn_dir/^*.zwc
		fpath=($zwc $fpath)
		autoload -Uwz $zwc
	fi
done; unset fn_dir zwc
