# ZSHRC
#
# This file is sourced by interactive shells.
# It should define aliases, functions, shell options, and key bindings.

# export variables
export EDITOR='vscode'
export VISUAL='vscode'
[[ $OSTYPE == darwin* ]] && export BROWSER='open' || export BROWSER='xdg-open'
export PAGER='less'
export LESS='-F -g -i -M -R -S -w'
export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory"
export HISTSIZE=1000
export SAVEHIST=1000
export TIMEFMT=$'\n\e[0;37m%J\n\e[1;35mreal\e[00m %*Es\t\e[1;35musr\e[00m %*Us\t\e[1;35msys\e[00m %*Ss\t\e[1;35mcpu\e[00m %P'
export DOTFILES=$HOME/code/notes/.dotfiles
export NVM_DIR=~/.nvm

# iterm
test -e $HOME/.iterm2_shell_integration.zsh && source $HOME/.iterm2_shell_integration.zsh
# zsh options
source $DOTFILES/zsh/options.zsh
# prezto
source $DOTFILES/zsh/prezto/init.zsh
# key bindings
[[ $OSTYPE == linux* ]] && source $DOTFILES/zsh/keybindings.zsh
# aliases
source $DOTFILES/zsh/aliases.zsh
# nvm
source $(brew --prefix nvm)/nvm.sh

# autoload compiled functions
for fn_dir in $DOTFILES/zsh/functions/*; do
	if [[ -d $fn_dir ]]; then
		zwc="${fn_dir}/${fn_dir:t}.zwc"
		zcompile -Uz $zwc $fn_dir/^*.zwc
		fpath=($zwc $fpath)
		autoload -Uwz $zwc
	fi
done; unset fn_dir zwc

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.composer/vendor/bin:/usr/local/mysql/bin:$PATH"
